### ISSUE TITLE
TypeError: mix.sassLost is not a function

### ISSUE THREAD

**Issue by ttocskcaj** [stefanoruth/laravel-elixir-lost#3]
I keep getting this error. Not sure if it's me or something wrong with the package.
I have elixir ^5.0.0. Here is my gulpfile.json
http://pastebin.com/9mpsELGX

**Comment by stefanoruth** [comment]
I see youre problem, it didnt worked here aswell so i have just updated the entire package to fit a newer version, yet i upgrade the package to minium support the version 6 of laravel-elixir, so i have no version for elixir 5, but you can try to upgrade to elixir 6 and use that instead.
